import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}


        <div id="container-9e91e2fa87bdcf9e767f1a072ea6b03f">
          <Script src="https://pl29750684.effectivecpmnetwork.com/9e91e2fa87bdcf9e767f1a072ea6b03f/invoke.js" />
          <Script src="https://pl29750683.effectivecpmnetwork.com/32/6c/34/326c34aae408c53f6177d1a30db9cc32.js" />
        </div>
      </body>
    </html>
  );
}
